### PR TITLE
Single tree view

### PR DESCRIPTION
**Pull request by tpetersen0308**
Built component for single tree view in src/SingleTree.js
Added css file for styling single tree component in src/SingleTree.css
Built temporary tree object to pass to SingleTree component as props pending database normalization.
- Object attributes are based on projected table schema in issue #16 

References to `props.tree` in the SingleTree component will likely need to be refactored to be consistent with the db schema once it has been normalized.

### CODE REVIEW

**Comment by emillipede** [comment]
Thanks @tpetersen0308 ! @Reltre can you please review this PR? If not, just let me know, I'll reassign it. 

Thank you both again!

**Comment by Reltre** [comment]
@emillipede Sure, I'll look it over.

**Comment by tpetersen0308** [comment]
@Reltre you bet. I'll resize it shortly.

**Comment by Reltre** [comment]
Ok, I think that should do it. We may want to mess with these files a bit in the future for mobile, but that is a ways off.

**Pull request merged**
